### ISSUE TITLE
Not working in Drone CI, but works locally with same repo

### ISSUE THREAD

**Issue by b-ferreira** [pantheon-systems/autotag#68]
Hello,

I'm trying to use `Autotag` in one of my pipelines in Drone CI.

I always get the following error message:
```
2021/12/10 10:14:26 Error initializing: no stable (non pre-release) version tags found
```

Here's my pipeline configuration:

```yaml
kind: pipeline
type: kubernetes
name: tag-repo

steps:
  - name: autotag
    image: node:14
    commands:
      - curl -sL https://git.io/autotag-install | sh -s -- -b /usr/bin
      - git --version
      - autotag -n -b dev

trigger:
  branch:
    - dev-ci
  event:
    - push
```

I'm adding `git --version` to make sure that I have `git 2.X+` available in the PATH.
And I'm using the `-n` option just to validate if `Autotag` is working correctly for now.

Here's the output:

```
1	+ curl -sL https://git.io/autotag-install | sh -s -- -b /usr/bin
2	pantheon-systems/autotag info checking GitHub for latest tag
3	pantheon-systems/autotag info found version: 1.3.13 for v1.3.13/linux/amd64
4	pantheon-systems/autotag info installed /usr/bin/autotag
32	+ git --version
33	git version 2.11.0
34	+ autotag -n -b dev
35	2021/12/10 10:14:26 Error initializing: no stable (non pre-release) version tags found
```

If I run the same command locally in the same repository it manages to compute the next tag normaly.

Is there any trick or extra configuration that I need to make this work in Drone CI?
